version: "3.7"

services:
  backend:
    build: ./backend
    working_dir: /backend
    container_name: backend
    command: python3 dev-entry.py
    volumes:
      - ./backend/:/backend/
    ports:
      - 8001:8000
    depends_on:
      - unknown_mongo
    env_file:
      - .env
  frontend:
    build: ./frontend
    container_name: frontend
    working_dir: /frontend
    command: node dev-entry.mjs
    volumes:
      - ./frontend/src/:/frontend/src/
      - ./frontend/static/:/frontend/static/
      - ./frontend/package.json:/frontend/package.json
      - ./frontend/package-lock.json:/frontend/package-lock.json
      - ./frontend/pnpm-lock.yaml:/frontend/pnpm-lock.yaml
      - ./frontend/tsconfig.json:/frontend/tsconfig.json

    depends_on:
      - unknown_mongo
    ports:
      - 5173:5173
    env_file:
      - .env
  unknown_mongo:
    image: mongo
    container_name: unknown_mongo
    restart: always
    env_file:
      - .env
    volumes:
      - "./data:/data/db"
