version: "3.7"

services:
  backend:
    build: ./backend
    working_dir: /backend
    container_name: backend
    command: python3 dev-entry.py
    volumes:
      - ./backend/:/backend
    depends_on:
      - unknown_mongo
    env_file:
      - .env
  frontend:
    build: ./frontend
    container_name: frontend
    working_dir: /frontend
    command: pnpm docker-dev
    volumes:
      - ./frontend/src/:/frontend/src/
      - ./frontend/static/:/frontend/static/
      - ./frontend/package.json:/frontend/package.json
    depends_on:
      - unknown_mongo
    env_file:
      - .env
  unknown_mongo:
    image: mongo
    container_name: unknown_mongo
    restart: always
    env_file:
      - .env
    volumes:
      - "./data:/data/db"
  client:
    image: nginx
    ports:
      - 2080:80
    volumes:
      - type: bind
        source: ./dev-proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    depends_on:
      - frontend
      - backend
